# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
install:
  - pip install cookiecutter
  - pip install invoke==1.0.0
  - nvm install 8.11.2
  - nvm use 8.11.2
script:
  - invoke test
